# Generated by Django 4.2.5 on 2023-12-21 12:21

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название продукта')),
                ('price', models.IntegerField(verbose_name='Price of product')),
                ('description', models.TextField(verbose_name='Description of product')),
                ('quantity', models.IntegerField(default='10', verbose_name='Quantity of product')),
                ('preview', models.ImageField(upload_to=store.models.Product.make_preview_path, verbose_name='Preview of product')),
                ('condition', models.CharField(blank=True, choices=[(None, ''), ('new', 'new'), ('popular', 'popular')], max_length=10, verbose_name='Condition of product')),
                ('slug', models.SlugField(default='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brands', verbose_name='Brand of product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Category of product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.ProductImage.make_preview_path, verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
